<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BooksShop</title>
</head>
<body>

<div class="menu">
    <a href="?page=default">Home</a>
    <a href="?page=books">Books</a>
    <a href="?page=author">Authors</a>
    <a href="?page=contact">Contact</a>
    <a href="?page=cart">My cart</a>
</div>
<hr>
<div class="content">
<?=$content?>
    <br>
    <br>
    <br>
    <br>
</div>
<hr>
<div class="footer">
    All rights reserved &copy; 2017
</div>

</body>
</html>